version: "3.7"
services:
  nginx:
    image: jwoo11/drogon:nginx
    depends_on:
      - webapp
    ports:
      - "8080:80"
    networks:
      - webnet
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 4g
      restart_policy:
        condition: on-failure
  webapp:
    image: jwoo11/drogon:server
    networks:
      - webnet
    volumes:
      - /models:/models
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.0"
          memory: 4g
      restart_policy:
        condition: on-failure

networks:
  webnet:
